
Argument 'size' of function realloc has a fishy (possibly negative) value: -1
   at 0x........: realloc (vg_replace_malloc.c:...)
   by 0x........: main (accounting.c:17)


HEAP SUMMARY:
    in use at exit: ... bytes in ... blocks
  total heap usage: ... allocs, ... frees, ... bytes allocated

For a detailed leak analysis, rerun with: --leak-check=full

For counts of detected and suppressed errors, rerun with: -v
ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
