#! /bin/sh

# Filters are not run for post-test check commands.
# Filter everything here.

echo "---Status---"
echo "::status" | /usr/bin/mdb vgcore.* | \
sed -i 's/\(.*\) from \S*$/from .../' | \
perl -0 -p -e 's/^file: .+?^(initial argv:)/$1/ms' | \
sed -i 's/addr=[0-9A-Fa-f]+/addr=......../g'

echo "\n---Stacks---"
echo "::stacks ! sed -i 's/^(\S+)\+.*/\$1/g'" | /usr/bin/mdb vgcore.* | \
sed -i 's/^(THREAD)\s+(STATE)\s+(SOBJ)\s+(COUNT)\s*$/$1 $2 $3 $4\n/' | \
sed -i 's/^(\d+)\s+(UNPARKED)\s+(\S+)\s+(\d+)/$1 $2 $3 $4/g' | \
sed -i 's/^\s*libc.*.so.1/libc.so.1/g' | \
sed -i 's/^\s*(coredump_many_threads)/$1/g' | \
sed -i 's/\+0x[0-9A-Fa-f]+//g'
