#! /bin/bash

die(){
  printf "$*" 1>&2 ;
  exit 1;
}



if [[ $# != 3 ]];then die "Illegal amount of args\n";fi

file1=$1
file2=$2

if [[ $3 == '1' ]];then
  patt='Failed while instrumentation list'
elif [[ $3 == '2' ]];then
  patt='Failed stderr list'
else
  die "\$3 = $3 can be only 1 or 2\n";
fi

printf "\npatt = \'$patt\'\n\n"


log1=$(cat $file1 | grep "$patt" | sed 's/\,//g' | sed "s/$patt//g")
log2=$(cat $file2 | grep "$patt" | sed 's/\,//g' | sed "s/$patt//g")

diff_num=0
for l2 in $log2;do
  contains=0
  for l1 in $log1;do
    if [[ $l2 == $l1 ]];then contains=1;fi
  done
  if [[ $contains == 0 ]];then printf "$l2 \n";((diff_num++));fi
done

printf "\n\npassed in x86, not passed in ppc = $diff_num\n\n"

diff_num=0
for l1 in $log1;do
  contains=0
  for l2 in $log2;do
    if [[ $l1 == $l2 ]];then contains=1;fi
  done
  if [[ $contains == 0 ]];then printf "$l1 \n";((diff_num++));fi
done

printf "\n\npassed in ppc, not passed in x86 = $diff_num\n\n"
